### ISSUE TITLE
ensure 5.2.0 is uploaded

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/chardet-feedstock#34]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Thanks for maintaining this!

It looks like while #33 was all :heavy_check_mark: , the merge to `main` did not actually upload anything:
 
https://github.com/conda-forge/chardet-feedstock/runs/15540708328

Perhaps one of the following would work, in order:
- rekicking the job?
- make a dummy commit/build number?
- rerendering?
- requesting the ci token is regenerated, a la [this PR](https://github.com/conda-forge/admin-requests/pull/783) ?

References:
- blocks https://github.com/conda-forge/tox-feedstock/pull/153

### Installed packages

```shell
ci
```

### Environment info

```shell
ci
```

**Comment by bollwyvl** [comment]
ping @conda-forge/chardet 

we're now two PRs deep on `tox` from this.

**Comment by dan-blanchard** [comment]
I don't see any unfinished/stuck jobs, so I'm not sure what the problem is here.

**Comment by bollwyvl** [comment]
Ah, indeed, looks like it re-ran (and uploaded) on the 18th. Sorry for the noise.
