### ISSUE TITLE
Import chardet fails with "module not found"

### ISSUE THREAD

**Issue by gabm** [conda-forge/chardet-feedstock#9]
Issue: Since the noarch update, chardet cannot be imported anymore.. this seems to be related to https://github.com/conda-forge/requests-feedstock/issues/23

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by gabm** [comment]
@jakirkham done,.. please see here https://github.com/conda-forge/chardet-feedstock/pull/11 and here https://github.com/conda-forge/idna-feedstock/pull/9

**Comment by gabm** [comment]
fixed via #11

**Comment by jschueller** [comment]
Thanks a lot @gabm
